### PR TITLE
Added support for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by mvdriel**

### CODE REVIEW

**Comment by mvdriel** [comment]
There seems to be an issue with the naming of network interfaces in Ubuntu 16.04:
```
==> ubuntu-1604: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ip addr flush dev eth1 2> /dev/null

Stdout from the command:



Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
```
@tersmitten Do you already have a solution for this?

**Comment by tersmitten** [comment]
This should be fixed in the next version of vagrant ([see](https://github.com/mitchellh/vagrant/issues/7155)), or maybe as a workaround in the 16.04 box.

**Comment by tersmitten** [comment]
@mvdriel The 16.04 machine fails on `vagrant up`, but if you issue a `vagrant provision` afterwards it works just fine :-)

**Comment by mvdriel** [comment]
@tersmitten Thanks!

**Comment by tersmitten** [comment]
Can you make the vagrant file like [this](https://raw.githubusercontent.com/Oefenweb/ansible-apparmor/master/Vagrantfile) and adjust the `meta` file?

**Comment by mvdriel** [comment]
Yes, done.

**Pull request merged**
